# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=20, null=True, verbose_name='渠道')),
                ('gameid', models.IntegerField(db_index=True, null=True, verbose_name='游戏id')),
                ('hostname', models.CharField(max_length=50, null=True, verbose_name='主机名')),
                ('servername', models.CharField(db_index=True, max_length=50, null=True, verbose_name='游戏区服名')),
                ('inner_ip', models.CharField(max_length=32, null=True, verbose_name='内网IP')),
                ('db_ip', models.CharField(max_length=32, null=True, verbose_name='DBIP')),
                ('status', models.SmallIntegerField(choices=[(0, '已关闭'), (1, '运行中')], default=0)),
            ],
            options={
                'db_table': 'games_server',
            },
        ),
    ]
